#!/usr/bin/env bash
# End-to-end for Phase 5: the 90-second loop. The CLI is the headline of
# this phase — this script proves `confer push`, `confer status`,
# `confer open`, and `confer skill install` work against a real running
# Confer server.
set -uo pipefail
cd "$(dirname "$0")/.."

export APP_ORIGIN=http://app.local
export VIEW_ORIGIN=http://view.local
export DB_PATH=./data/e2e5.db
export BLOB_DIR=./blobs
export SIGNING_SECRET=dev-only-change-me
export PORT=8791

rm -f "$DB_PATH" "$DB_PATH-wal" "$DB_PATH-shm" 2>/dev/null
rm -rf "$BLOB_DIR"
mkdir -p data blobs

# Temp config and HTML
CFG_DIR=$(mktemp -d)
CFG="$CFG_DIR/config.json"
HTML="$CFG_DIR/doc.html"
cat > "$HTML" <<'EOF'
<!doctype html>
<html><body>
<h1>Auth flow (CLI E2E)</h1>
<p>Generated by confer push in scripts/e2e-phase5.sh.</p>
</body></html>
EOF

# 1) Seed
echo "== seed =="
SEED=$(npx tsx --env-file=.env server/src/dev/seed.ts)
PUSH_TOK=$(echo "$SEED" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>console.log(JSON.parse(d).pushToken))')
MCP_TOK=$(echo "$SEED" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>console.log(JSON.parse(d).mcpToken))')
SESSION=$(echo "$SEED" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>console.log(JSON.parse(d).sessionCookie))')
USER=$(echo "$SEED" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>console.log(JSON.parse(d).userId))')
echo "  push_tok=${PUSH_TOK:0:12}…"

# Write the CLI config so `confer` picks up server + push token automatically.
cat > "$CFG" <<EOF
{ "server": "http://localhost:$PORT", "pushToken": "$PUSH_TOK" }
EOF
export CONFER_CONFIG="$CFG"

# 2) Boot the server
echo "== boot server =="
npx tsx --env-file=.env server/src/index.ts > /tmp/confer-phase5.log 2>&1 &
PID=$!
trap "kill $PID 2>/dev/null; rm -rf $CFG_DIR" EXIT
for i in 1 2 3 4 5 6 7 8 9 10; do
  curl -fsS "http://localhost:$PORT/health" >/dev/null 2>&1 && break
  sleep 0.3
done
curl -fsS "http://localhost:$PORT/health" >/dev/null || { echo "FAIL: server didn't start"; cat /tmp/confer-phase5.log; exit 1; }
echo "  server up on :$PORT"

# 3) confer push — the headline
echo "== confer push =="
PUSH_OUT=$(npx tsx cli/src/index.ts push "$HTML" --space backend --slug auth-flow 2>&1)
echo "  $PUSH_OUT"
VID=$(echo "$PUSH_OUT" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>console.log(JSON.parse(d).version_id))')
[ -n "$VID" ] || { echo "FAIL: no version_id"; exit 1; }
echo "  ✓ version_id=$VID"

# 4) Approve the version via REST
echo "== approve via REST =="
curl -fsS -X POST "http://localhost:$PORT/api/v1/versions/$VID/approve" -H "Cookie: $SESSION" >/dev/null
echo "  ✓ approved"

# 5) confer open --print — prints the review URL
echo "== confer open --print =="
OPEN_OUT=$(npx tsx cli/src/index.ts open --print 2>&1)
echo "  $OPEN_OUT"
echo "$OPEN_OUT" | grep -q "/v/$VID" || { echo "FAIL: open should print the review URL of $VID"; exit 1; }
echo "  ✓"

# 6) confer status — via MCP, sees the approved doc
echo "== confer status (via MCP) =="
# Status uses the push token by default; the push token only has 'push' scope.
# We need an mcp-scoped token for status. Set CONFER_MCP_TOKEN for this call.
export CONFER_MCP_TOKEN="$MCP_TOK"
STATUS_OUT=$(npx tsx cli/src/index.ts status --space backend 2>&1)
echo "  $STATUS_OUT"
echo "$STATUS_OUT" | grep -q "auth-flow" || { echo "FAIL: status should show auth-flow"; exit 1; }
echo "$STATUS_OUT" | grep -q "approved" || { echo "FAIL: status should show approved state"; exit 1; }
echo "  ✓"

# 7) confer skill install — copies SKILL.md to a temp dir
echo "== confer skill install =="
SKILL_DIR=$(mktemp -d)
npx tsx cli/src/index.ts skill install --dir "$SKILL_DIR" >/dev/null
[ -f "$SKILL_DIR/SKILL.md" ] || { echo "FAIL: SKILL.md not installed"; exit 1; }
grep -q "name: confer" "$SKILL_DIR/SKILL.md" || { echo "FAIL: SKILL.md missing name"; exit 1; }
grep -q "GitHub PRs for docs" "$SKILL_DIR/SKILL.md" || { echo "FAIL: SKILL.md missing tagline"; exit 1; }
grep -q "product invariant" "$SKILL_DIR/SKILL.md" || { echo "FAIL: SKILL.md missing invariant"; exit 1; }
echo "  ✓ SKILL.md installed at $SKILL_DIR/SKILL.md ($(wc -l < "$SKILL_DIR/SKILL.md") lines)"
rm -rf "$SKILL_DIR"

# 8) confer help / unknown command
echo "== confer --help =="
HELP=$(npx tsx cli/src/index.ts --help 2>&1)
echo "$HELP" | grep -q "confer push" || { echo "FAIL: help missing push"; exit 1; }
echo "  ✓"
UNKNOWN=$(npx tsx cli/src/index.ts bogus >/dev/null 2>&1; echo $?)
[ "$UNKNOWN" = "2" ] || { echo "FAIL: expected exit 2 for unknown subcommand, got $UNKNOWN"; exit 1; }
echo "  ✓ unknown subcommand exits 2"

# 9) confer login writes the config
echo "== confer login --server --token =="
NEW_CFG=$(mktemp)
CONFER_CONFIG="$NEW_CFG" npx tsx cli/src/index.ts login --server http://cli.test --token confer_test >/dev/null 2>&1
CFG_BACK=$(cat "$NEW_CFG")
echo "  config: $CFG_BACK"
echo "$CFG_BACK" | grep -q "http://cli.test" || { echo "FAIL: login didn't persist server"; exit 1; }
echo "$CFG_BACK" | grep -q "confer_test" || { echo "FAIL: login didn't persist token"; exit 1; }
echo "  ✓"
rm -f "$NEW_CFG"

echo ""
echo "ALL PHASE-5 E2E ASSERTIONS PASSED"
